// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId, 
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { TttBoard as __TttBoard } from "./ttt_board_type";
import { Connect4 as __Connect4 } from "./connect_4_type";
import { SpacetimeGoBoard as __SpacetimeGoBoard } from "./spacetime_go_board_type";

// A namespace for generated variants and helper functions.
export namespace DbBoardGame {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type TicTacToe = { tag: "TicTacToe", value: __TttBoard };
  export type Connect4 = { tag: "Connect4", value: __Connect4 };
  export type Go = { tag: "Go", value: __SpacetimeGoBoard };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const TicTacToe = (value: __TttBoard): DbBoardGame => ({ tag: "TicTacToe", value });
  export const Connect4 = (value: __Connect4): DbBoardGame => ({ tag: "Connect4", value });
  export const Go = (value: __SpacetimeGoBoard): DbBoardGame => ({ tag: "Go", value });

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("TicTacToe", __TttBoard.getTypeScriptAlgebraicType()),
      new SumTypeVariant("Connect4", __Connect4.getTypeScriptAlgebraicType()),
      new SumTypeVariant("Go", __SpacetimeGoBoard.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DbBoardGame): void {
      DbBoardGame.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DbBoardGame {
      return DbBoardGame.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `DbBoardGame`.
export type DbBoardGame = DbBoardGame.TicTacToe | DbBoardGame.Connect4 | DbBoardGame.Go;

export default DbBoardGame;

