// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId, 
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Player as __Player } from "./player_type";
import { LinkNode as __LinkNode } from "./link_node_type";
import { Zobrist as __Zobrist } from "./zobrist_type";
import { LinkHead as __LinkHead } from "./link_head_type";

export type Group = {
  color: __Player,
  libertyEdgeCount: number,
  zobrist: __Zobrist,
  stones: __LinkHead,
  deadLink: __LinkNode,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Group {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("color", __Player.getTypeScriptAlgebraicType()),
      new ProductTypeElement("libertyEdgeCount", AlgebraicType.createU16Type()),
      new ProductTypeElement("zobrist", __Zobrist.getTypeScriptAlgebraicType()),
      new ProductTypeElement("stones", __LinkHead.getTypeScriptAlgebraicType()),
      new ProductTypeElement("deadLink", __LinkNode.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Group): void {
    Group.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Group {
    return Group.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


