// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId, 
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Player as __Player } from "./player_type";
import { Rules as __Rules } from "./rules_type";
import { Chains as __Chains } from "./chains_type";
import { State as __State } from "./state_type";
import { Komi as __Komi } from "./komi_type";

export type SpacetimeGoBoard = {
  rules: __Rules,
  chains: __Chains,
  nextPlayer: __Player,
  state: __State,
  komi: __Komi,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SpacetimeGoBoard {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("rules", __Rules.getTypeScriptAlgebraicType()),
      new ProductTypeElement("chains", __Chains.getTypeScriptAlgebraicType()),
      new ProductTypeElement("nextPlayer", __Player.getTypeScriptAlgebraicType()),
      new ProductTypeElement("state", __State.getTypeScriptAlgebraicType()),
      new ProductTypeElement("komi", __Komi.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SpacetimeGoBoard): void {
    SpacetimeGoBoard.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SpacetimeGoBoard {
    return SpacetimeGoBoard.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


