// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId, 
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { OptionU16 as __OptionU16 } from "./option_u_16_type";
import { LinkNode as __LinkNode } from "./link_node_type";

export type TileContent = {
  groupId: __OptionU16,
  link: __LinkNode,
  hasHadStone: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace TileContent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("groupId", __OptionU16.getTypeScriptAlgebraicType()),
      new ProductTypeElement("link", __LinkNode.getTypeScriptAlgebraicType()),
      new ProductTypeElement("hasHadStone", AlgebraicType.createU8Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TileContent): void {
    TileContent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TileContent {
    return TileContent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


