// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId, 
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { VersusGameInstance } from "./versus_game_instance_type";
import { DbBoardGameParam as __DbBoardGameParam } from "./db_board_game_param_type";
import { Player as __Player } from "./player_type";
import { Outcome as __Outcome } from "./outcome_type";
import { DbBoardGame as __DbBoardGame } from "./db_board_game_type";

import type { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `versus_game_instance`.
 *
 * Obtain a handle from the [`versusGameInstance`] property on [`RemoteTables`],
 * like `ctx.db.versusGameInstance`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.versusGameInstance.on_insert(...)`.
 */
export class VersusGameInstanceTableHandle {
  tableCache: TableCache<VersusGameInstance>;

  constructor(tableCache: TableCache<VersusGameInstance>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<VersusGameInstance> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `versus_game_instance`,
   * which allows point queries on the field of the same name
   * via the [`VersusGameInstanceIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.versusGameInstance.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `versus_game_instance`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): VersusGameInstance | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: VersusGameInstance) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: VersusGameInstance) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: VersusGameInstance) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: VersusGameInstance) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: VersusGameInstance, newRow: VersusGameInstance) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: VersusGameInstance, newRow: VersusGameInstance) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
