name: App CI

on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'bg-app/**'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  build-bg-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat bg-app/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set suffix based on branch
        id: set_suffix
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "SUFFIX=dev" >> $GITHUB_OUTPUT
          else
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          fi          

      - name: Build and push Docker image
        uses: BastianGanze/checkout-build-push-docker@v1.0.8
        with:
          image-name: bg-app
          suffix: ${{ steps.set_suffix.outputs.SUFFIX }}
          version: ${{ steps.get_version.outputs.VERSION }}