name: CMS CI

on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'bg-cms/**'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  build-bg-cms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat bg-cms/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set suffix based on branch
        id: set_suffix
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "SUFFIX=dev" >> $GITHUB_OUTPUT
          else
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          fi          

      - name: Build and push Docker image
        uses: BastianGanze/checkout-build-push-docker@v1.0.6
        with:
          image-name: bg-cms
          suffix: ${{ steps.set_suffix.outputs.SUFFIX }}
          version: ${{ steps.get_version.outputs.VERSION }}
          build-args: |
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_PORT: ${{ secrets.DB_PORT }}
            SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
            CORS: "https://bastianganze.me"